### ISSUE TITLE
클라이언트 수정사항 누락

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/sampyo#192]
## ver3

pptx 11 ~ 18 클라이언트에게 어떤 수정사항인지 다시한번 체크필요

## ver4

<table>
<tr>
	<th>pptx number
	<th>content
<tr>
	<td>1
	<td>퀵메뉴 관련 디자인 없음
<tr>
	<td>2
	<td>영상속도 조절된 영상 없음 or 필요
<tr>
	<td>7
	<td>이미지 위치 교체완료, 하지만 고화질 이미지 (제플린 필요)
<tr>
	<td>8
	<td>이미지 변경 (제플린 필요)
<tr>
	<td>10
	<td>이미지 변경 (제플린 필요)
<tr>
	<td>13
	<td>이미지 변경 (제플린 필요)
<tr>
	<td>14
	<td>10번과 동일한 이미지
</table>

_Originally posted by @Hansanghyeon in https://github.com/beeclover/sampyo/issues/189#issuecomment-970050989_

**Comment by Hansanghyeon** [comment]
## TODOs

- [ ] 1. 퀵메뉴 관련 디자인 없음
- [ ] 2. 영상속도 조절된 영상 없음 or 필요
- [ ] 7. 이미지 위치 교체완료, 하지만 고화질 이미지 (제플린 필요)
- [ ] 8. 이미지 변경 (제플린 필요)
- [ ] 10. 이미지 변경 (제플린 필요)
- [ ] 13. 이미지 변경 (제플린 필요)
- [ ] 14. 10번과 동일한 이미지
